@echo off
echo 正在禁用Windows自动更新...
echo.

echo 1. 停止Windows更新服务...
net stop wuauserv

echo 2. 禁用Windows更新服务...
sc config wuauserv start= disabled

echo 3. 停止Windows更新医疗服务...
net stop UsoSvc

echo 4. 禁用Windows更新医疗服务...
sc config UsoSvc start= disabled

echo 5. 停止Windows更新Orchestrator服务...
net stop WaaSMedicSvc

echo 6. 禁用Windows更新Orchestrator服务...
sc config WaaSMedicSvc start= disabled

echo 7. 通过组策略禁用自动更新...
reg add "HKLM\SOFTWARE\Policies\Microsoft\Windows\WindowsUpdate\AU" /v NoAutoUpdate /t REG_DWORD /d 1 /f

echo 8. 禁用自动下载和安装...
reg add "HKLM\SOFTWARE\Policies\Microsoft\Windows\WindowsUpdate\AU" /v AUOptions /t REG_DWORD /d 2 /f

echo 9. 禁用计划安装...
reg add "HKLM\SOFTWARE\Policies\Microsoft\Windows\WindowsUpdate\AU" /v ScheduledInstallDay /t REG_DWORD /d 0 /f

echo 10. 禁用自动重启...
reg add "HKLM\SOFTWARE\Policies\Microsoft\Windows\WindowsUpdate\AU" /v NoAutoRebootWithLoggedOnUsers /t REG_DWORD /d 1 /f

echo.
echo Windows自动更新已成功禁用！
echo 按任意键退出...
pause > nul